import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { GoogleGenAI } from "@google/genai";
import { 
  AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, 
  BarChart, Bar, Legend, ReferenceLine
} from 'recharts';
import { getAssessment, getAssessmentReport, getAssessmentAI } from '../api/assessment';
import { addToHistory } from '../utils/history';
import { AssessmentResponse } from '../types';
// @ts-ignore
import html2pdf from 'html2pdf.js';
// @ts-ignore
import { marked } from 'marked';

const ResultsPage: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const [data, setData] = useState<AssessmentResponse | null>(null);
  const [reportMd, setReportMd] = useState<string>('');
  const [aiMd, setAiMd] = useState<string>('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  
  // Gemini Suggestion State
  const [geminiSuggestion, setGeminiSuggestion] = useState<string>('');
  const [isGeminiThinking, setIsGeminiThinking] = useState(false);

  useEffect(() => {
    if (!id) return;

    const fetchData = async () => {
      try {
        const assessment = await getAssessment(id);
        
        const [report, ai] = await Promise.all([
          getAssessmentReport(id).catch(err => {
            console.warn('Failed to fetch report', err);
            return '';
          }),
          getAssessmentAI(id).catch(err => {
            console.warn('Failed to fetch AI report', err);
            return '';
          })
        ]);

        setData(assessment);
        setReportMd(report);
        setAiMd(ai);

        addToHistory({
          id: assessment.id,
          company: assessment.company,
          industry: assessment.industry,
          created_at: assessment.created_at,
        });

      } catch (err: any) {
        console.error(err);
        setError(err.message || 'Failed to load assessment results.');
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, [id]);

  const handleDownloadMd = () => {
    if (!reportMd) return;
    const blob = new Blob([reportMd], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${data?.company || 'assessment'}_report.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleDownloadPDF = async () => {
    if (!reportMd) return;

    try {
      // Parse markdown to HTML
      const htmlContent = marked.parse(reportMd);

      const element = document.createElement('div');
      element.innerHTML = `
        <div style="font-family: Helvetica, Arial, sans-serif; padding: 20px; color: #333;">
          <div style="border-bottom: 2px solid #2563eb; padding-bottom: 10px; margin-bottom: 20px;">
            <h1 style="font-size: 24px; font-weight: bold; margin: 0; color: #2563eb;">${data?.company || 'Company'}</h1>
            <p style="margin: 5px 0 0; font-size: 14px; color: #666;">Financial Health Assessment Report</p>
            <p style="margin: 5px 0 0; font-size: 12px; color: #999;">
              Industry: ${data?.industry} | Date: ${new Date().toLocaleDateString()}
            </p>
          </div>
          <div style="line-height: 1.5; font-size: 12px;">
            ${htmlContent}
          </div>
          <div style="margin-top: 30px; border-top: 1px solid #eee; padding-top: 10px; font-size: 10px; text-align: center; color: #999;">
            Generated by SME Financial Health Assessment Platform
          </div>
        </div>
      `;

      const opt = {
        margin:       10,
        filename:     `${data?.company || 'Assessment'}_Report.pdf`,
        image:        { type: 'jpeg', quality: 0.98 },
        html2canvas:  { scale: 2 },
        jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' }
      };

      html2pdf().set(opt).from(element).save();

    } catch (e) {
      console.error("PDF generation failed", e);
      alert("Failed to generate PDF. Please try again.");
    }
  };

  const generateGeminiSuggestions = async () => {
    if (!reportMd) return;
    
    const apiKey = process.env.API_KEY;
    if (!apiKey) {
      alert("API_KEY is not configured in the environment.");
      return;
    }

    setIsGeminiThinking(true);
    try {
      const ai = new GoogleGenAI({ apiKey });
      const prompt = `
        You are an expert SME financial advisor. Based on the provided financial report, generate a concise strategic brief for the business owner including:
        1. **Creditworthiness Evaluation**: Assess their ability to get loans.
        2. **Risk Analysis**: Identify top 2 critical financial risks.
        3. **Cost Optimization**: Suggest 2 specific areas to cut costs.
        4. **Financial Products**: Recommend suitable banking products (e.g., Working Capital Loan, Invoice Discounting, Business Credit Card) based on their situation.
        5. **Compliance**: Flag any potential tax or compliance gaps if visible.
        
        Keep it professional, actionable, and suitable for a non-finance business owner.
        
        Report Content:
        ${reportMd}
      `;
      
      const response = await ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents: prompt,
      });
      setGeminiSuggestion(response.text || 'No suggestions generated.');
    } catch (e) {
      console.error('Gemini API Error:', e);
      setGeminiSuggestion('Error generating suggestions. Please check the console or API key.');
    } finally {
      setIsGeminiThinking(false);
    }
  };

  if (loading) return (
    <div className="flex justify-center items-center h-64">
      <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
    </div>
  );
  
  if (error) return (
    <div className="max-w-7xl mx-auto py-10 px-4">
      <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded relative" role="alert">
        <strong className="font-bold">Error: </strong>
        <span className="block sm:inline">{error}</span>
      </div>
    </div>
  );
  
  if (!data || !data.result_json) return <div className="text-center py-20 text-gray-500">No data found.</div>;

  const { result_json: res } = data;

  // Prepare data for charts
  const forecastData = res.forecast?.forecast.map(item => ({
    name: item.month,
    Revenue: item.forecast_revenue,
    Expense: item.forecast_expense,
    Profit: item.forecast_operating_profit
  })) || [];

  return (
    <div className="max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:px-8 space-y-8">
      
      {/* Header */}
      <div className="bg-white shadow rounded-lg px-6 py-5 border-l-4 border-blue-600">
        <h1 className="text-3xl font-bold text-gray-900">{data.company}</h1>
        <div className="mt-2 text-sm text-gray-500 flex flex-wrap gap-4 items-center">
          <span className="bg-blue-100 text-blue-800 px-3 py-1 rounded-full font-medium">{data.industry}</span>
          <span>{new Date(data.created_at).toLocaleDateString()}</span>
          <span className="font-mono text-xs text-gray-400">{data.id}</span>
          <span className="bg-gray-100 px-2 py-1 rounded border border-gray-200 text-xs">Lang: {data.lang}</span>
        </div>
      </div>

      {/* Scores Grid */}
      {res.scores && (
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          {[
            { label: 'Health Score', value: res.scores.health_score, color: res.scores.health_score > 70 ? 'text-green-600' : 'text-blue-600' },
            { label: 'Risk Score', value: res.scores.risk_score, color: res.scores.risk_score < 30 ? 'text-green-600' : 'text-red-600' },
            { label: 'Credit Readiness', value: res.scores.credit_readiness_score, color: 'text-purple-600' },
            { label: 'Rating', value: res.scores.rating, color: 'text-gray-800' },
          ].map((score) => (
            <div key={score.label} className="bg-white overflow-hidden shadow-sm rounded-lg p-6 text-center border border-gray-100 hover:shadow-md transition-shadow">
              <dt className="text-sm font-medium text-gray-500 uppercase tracking-wide">{score.label}</dt>
              <dd className={`mt-2 text-4xl font-extrabold ${score.color}`}>{score.value}</dd>
            </div>
          ))}
        </div>
      )}

      {/* CHARTS SECTION */}
      {forecastData.length > 0 && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          
          {/* Revenue vs Expense Chart */}
          <div className="bg-white shadow rounded-lg p-6 border border-gray-100">
            <h3 className="text-lg font-bold text-gray-900 mb-4">Financial Projections (6 Months)</h3>
            <div className="h-72">
              <ResponsiveContainer width="100%" height="100%">
                <AreaChart data={forecastData} margin={{ top: 10, right: 30, left: 0, bottom: 0 }}>
                  <defs>
                    <linearGradient id="colorRevenue" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#2563eb" stopOpacity={0.1}/>
                      <stop offset="95%" stopColor="#2563eb" stopOpacity={0}/>
                    </linearGradient>
                    <linearGradient id="colorExpense" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#ef4444" stopOpacity={0.1}/>
                      <stop offset="95%" stopColor="#ef4444" stopOpacity={0}/>
                    </linearGradient>
                  </defs>
                  <XAxis dataKey="name" fontSize={12} tickLine={false} axisLine={false} />
                  <YAxis fontSize={12} tickLine={false} axisLine={false} tickFormatter={(value) => `${value / 1000}k`} />
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e5e7eb" />
                  <Tooltip 
                    contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)' }}
                    formatter={(value: number) => [`$${value.toLocaleString()}`, '']}
                  />
                  <Legend />
                  <Area type="monotone" dataKey="Revenue" stroke="#2563eb" strokeWidth={2} fillOpacity={1} fill="url(#colorRevenue)" />
                  <Area type="monotone" dataKey="Expense" stroke="#ef4444" strokeWidth={2} fillOpacity={1} fill="url(#colorExpense)" />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          </div>

          {/* Operating Profit Chart */}
          <div className="bg-white shadow rounded-lg p-6 border border-gray-100">
             <h3 className="text-lg font-bold text-gray-900 mb-4">Operating Profit Forecast</h3>
             <div className="h-72">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={forecastData} margin={{ top: 10, right: 30, left: 0, bottom: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e5e7eb" />
                  <XAxis dataKey="name" fontSize={12} tickLine={false} axisLine={false} />
                  <YAxis fontSize={12} tickLine={false} axisLine={false} tickFormatter={(value) => `${value / 1000}k`} />
                  <Tooltip 
                    cursor={{fill: '#f3f4f6'}}
                    contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)' }}
                    formatter={(value: number) => [`$${value.toLocaleString()}`, 'Profit']}
                  />
                  <ReferenceLine y={0} stroke="#9ca3af" />
                  <Bar dataKey="Profit" fill="#10b981" radius={[4, 4, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
             </div>
          </div>
        </div>
      )}

      {/* KPI Cards */}
      {res.kpis && (
        <div className="bg-white shadow rounded-lg overflow-hidden">
          <div className="px-6 py-5 border-b border-gray-200 bg-gray-50">
            <h3 className="text-lg leading-6 font-medium text-gray-900">Key Performance Indicators</h3>
          </div>
          <div className="px-6 py-5 grid grid-cols-2 md:grid-cols-4 gap-6">
            <div>
              <p className="text-xs font-semibold text-gray-500 uppercase">Revenue (LTM)</p>
              <p className="text-xl font-medium text-gray-900 mt-1">{res.kpis.total_revenue?.toLocaleString() ?? '-'}</p>
            </div>
            <div>
              <p className="text-xs font-semibold text-gray-500 uppercase">Total Expense (LTM)</p>
              <p className="text-xl font-medium text-gray-900 mt-1">{res.kpis.total_expense?.toLocaleString() ?? '-'}</p>
            </div>
            <div>
              <p className="text-xs font-semibold text-gray-500 uppercase">Operating Margin</p>
              <p className={`text-xl font-medium mt-1 ${res.kpis.operating_margin > 0 ? 'text-green-600' : 'text-red-600'}`}>
                {res.kpis.operating_margin ? (res.kpis.operating_margin * 100).toFixed(1) + '%' : '-'}
              </p>
            </div>
            <div>
              <p className="text-xs font-semibold text-gray-500 uppercase">Cash Runway</p>
              <p className={`text-xl font-medium mt-1 ${res.kpis.runway_months_proxy < 3 ? 'text-red-600' : 'text-gray-900'}`}>
                {res.kpis.runway_months_proxy?.toFixed(1) ?? '-'} Months
              </p>
            </div>
            <div className="col-span-2 md:col-span-4 border-t border-gray-100 pt-4 grid grid-cols-3 gap-4">
              <div>
                <p className="text-xs text-gray-500">DSO (Days Sales Outstanding)</p>
                <p className="font-semibold">{res.kpis.dso_days?.toFixed(0) ?? '-'}</p>
              </div>
              <div>
                <p className="text-xs text-gray-500">DPO (Days Payable Outstanding)</p>
                <p className="font-semibold">{res.kpis.dpo_days?.toFixed(0) ?? '-'}</p>
              </div>
              <div>
                <p className="text-xs text-gray-500">EMI / Monthly Revenue</p>
                <p className="font-semibold">{res.kpis.emi_to_monthly_revenue ? (res.kpis.emi_to_monthly_revenue * 100).toFixed(1) + '%' : '-'}</p>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Risks Table */}
      {res.risks && (
        <div className="bg-white shadow rounded-lg overflow-hidden">
          <div className="px-6 py-4 border-b border-gray-200 bg-gray-50 flex justify-between items-center">
            <h3 className="text-lg font-medium text-gray-900">Risk Assessment</h3>
            <span className="bg-red-100 text-red-800 text-xs px-2 py-1 rounded-full">{res.risks.length} Signals</span>
          </div>
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Severity</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Type</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Signal</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Reason</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {res.risks.map((risk, idx) => (
                  <tr key={idx} className="hover:bg-gray-50 transition-colors">
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={`px-2 py-1 inline-flex text-xs leading-5 font-semibold rounded-full 
                        ${(risk.severity || '').toLowerCase() === 'high' ? 'bg-red-100 text-red-800' : 
                          (risk.severity || '').toLowerCase() === 'medium' ? 'bg-yellow-100 text-yellow-800' : 'bg-green-100 text-green-800'}`}>
                        {risk.severity}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{risk.type}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">{risk.signal}</td>
                    <td className="px-6 py-4 text-sm text-gray-600">{risk.why}</td>
                  </tr>
                ))}
                {res.risks.length === 0 && (
                  <tr>
                    <td colSpan={4} className="px-6 py-8 text-center text-sm text-gray-500">
                      <div className="flex flex-col items-center">
                        <span className="text-green-500 text-2xl mb-2">✓</span>
                        No significant risks detected.
                      </div>
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Recommendations List */}
      {res.recommendations && res.recommendations.length > 0 && (
        <div className="bg-white shadow rounded-lg overflow-hidden">
          <div className="px-6 py-5 border-b border-gray-200 bg-gray-50">
            <h3 className="text-lg leading-6 font-medium text-gray-900">Strategic Recommendations</h3>
          </div>
          <div className="divide-y divide-gray-200">
            {res.recommendations.map((rec, idx) => (
              <div key={idx} className="p-6 hover:bg-gray-50 transition-colors">
                <div className="flex flex-col md:flex-row md:justify-between md:items-start gap-4">
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-2">
                       <h4 className="text-lg font-bold text-gray-900">{rec.title}</h4>
                       <span className="md:hidden inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                        {rec.impact_estimate} Impact
                      </span>
                    </div>
                    <p className="text-sm text-gray-600 mb-3">{rec.why}</p>
                    <div className="bg-blue-50 rounded-lg p-3">
                      <p className="text-xs font-bold text-blue-700 uppercase mb-2">Action Plan</p>
                      <ul className="space-y-1">
                        {(rec.actions || []).map((action, i) => (
                          <li key={i} className="text-sm text-blue-900 flex items-start gap-2">
                            <span className="text-blue-500 mt-1">•</span> {action}
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                  <span className="hidden md:inline-flex items-center px-3 py-1 rounded-full text-sm font-medium bg-blue-100 text-blue-800 whitespace-nowrap">
                    {rec.impact_estimate} Impact
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Detailed Forecast Table (Collapsible) */}
      <details className="bg-white shadow rounded-lg overflow-hidden group">
        <summary className="px-6 py-4 cursor-pointer font-medium text-gray-700 bg-gray-50 hover:bg-gray-100 transition-colors flex justify-between items-center">
          <span>View Detailed Forecast Data Table</span>
          <span className="text-gray-400 group-open:rotate-180 transition-transform">▼</span>
        </summary>
        <div className="overflow-x-auto border-t border-gray-200">
            <table className="min-w-full divide-y divide-gray-200 text-sm">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-6 py-3 text-left font-medium text-gray-500">Month</th>
                  <th className="px-6 py-3 text-right font-medium text-gray-500">Rev Forecast</th>
                  <th className="px-6 py-3 text-right font-medium text-gray-500">Exp Forecast</th>
                  <th className="px-6 py-3 text-right font-medium text-gray-500">Op Profit</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200">
                {res.forecast?.forecast.map((f, i) => (
                  <tr key={i}>
                    <td className="px-6 py-3 whitespace-nowrap text-gray-900">{f.month}</td>
                    <td className="px-6 py-3 whitespace-nowrap text-right text-gray-600">{f.forecast_revenue?.toLocaleString()}</td>
                    <td className="px-6 py-3 whitespace-nowrap text-right text-gray-600">{f.forecast_expense?.toLocaleString()}</td>
                    <td className={`px-6 py-3 whitespace-nowrap text-right font-medium ${f.forecast_operating_profit >= 0 ? 'text-green-600' : 'text-red-600'}`}>
                      {f.forecast_operating_profit?.toLocaleString()}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
      </details>

      {/* Breakdowns */}
      {res.breakdowns && (
        <div className="bg-white shadow rounded-lg overflow-hidden">
          <div className="px-6 py-5 border-b border-gray-200">
            <h3 className="text-lg leading-6 font-medium text-gray-900">Financial Breakdowns</h3>
          </div>
          <div className="px-6 py-5 bg-gray-50">
            <pre className="text-xs text-gray-600 overflow-auto max-h-48">{JSON.stringify(res.breakdowns, null, 2)}</pre>
          </div>
        </div>
      )}

      {/* Benchmarks */}
      {res.benchmarks && res.benchmarks.available && (
        <div className="bg-white shadow rounded-lg p-6">
          <h3 className="text-lg font-medium text-gray-900 mb-4">Industry Benchmarks ({res.benchmarks.industry})</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {Object.entries(res.benchmarks.benchmarks || {}).map(([key, val]) => (
              <div key={key} className="border p-4 rounded bg-gray-50">
                <span className="block text-xs font-bold text-gray-500 uppercase tracking-wider">{key.replace(/_/g, ' ')}</span>
                <div className="flex justify-between items-end mt-2">
                   <div>
                     <span className="text-xs text-gray-400">Industry Avg</span>
                     <p className="font-semibold text-gray-700">{val as React.ReactNode}</p>
                   </div>
                   <div className="text-right">
                     <span className="text-xs text-gray-400">You</span>
                     <p className={`font-semibold ${res.benchmarks.gaps?.[key] === 'Low' ? 'text-green-600' : 'text-blue-600'}`}>
                       {res.benchmarks.your?.[key]}
                     </p>
                   </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Gemini Suggestions */}
      <div className="bg-white shadow rounded-lg overflow-hidden border border-indigo-200">
        <div className="px-6 py-5 border-b border-indigo-100 bg-indigo-50 flex justify-between items-center">
          <div className="flex items-center gap-2">
            <span className="text-xl">✨</span>
            <h3 className="text-lg leading-6 font-medium text-indigo-900">Gemini AI Advisor</h3>
          </div>
          {!geminiSuggestion && !isGeminiThinking && (
             <button
              onClick={generateGeminiSuggestions}
              disabled={!reportMd}
              className="inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50 transition-colors"
            >
              Generate Insights
            </button>
          )}
        </div>
        
        {isGeminiThinking && (
          <div className="px-6 py-8 bg-white flex flex-col items-center justify-center">
             <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600 mb-2"></div>
             <p className="text-sm text-indigo-600 animate-pulse">Analyzing report data for Creditworthiness, Risks & Opportunities...</p>
          </div>
        )}

        {geminiSuggestion && (
          <div className="px-6 py-6 bg-white">
            <div className="prose prose-sm prose-indigo max-w-none text-gray-700 whitespace-pre-wrap">
              {geminiSuggestion}
            </div>
             <div className="mt-4 pt-4 border-t border-gray-100 flex justify-end">
               <button
                onClick={generateGeminiSuggestions}
                className="text-xs text-indigo-600 hover:text-indigo-800 font-medium hover:underline"
              >
                Regenerate Analysis
              </button>
             </div>
          </div>
        )}
      </div>

      {/* AI Analysis (Backend) */}
      {aiMd && (
        <div className="bg-white shadow rounded-lg overflow-hidden border border-purple-200">
          <div className="px-6 py-5 border-b border-purple-100 bg-purple-50">
            <h3 className="text-lg leading-6 font-medium text-purple-900">Deep Dive Analysis (Backend AI)</h3>
          </div>
          <div className="px-6 py-5 bg-white overflow-auto max-h-[500px]">
            <pre className="whitespace-pre-wrap text-sm text-gray-800 font-mono">{aiMd}</pre>
          </div>
        </div>
      )}

      {/* Report Markdown */}
      <div className="bg-white shadow rounded-lg overflow-hidden">
        <div className="px-6 py-5 border-b border-gray-200 flex justify-between items-center">
          <h3 className="text-lg leading-6 font-medium text-gray-900">Full Assessment Report</h3>
          <div className="flex gap-2">
            <button 
              onClick={handleDownloadMd}
              disabled={!reportMd}
              className={`inline-flex items-center px-3 py-1.5 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none transition-colors ${!reportMd ? 'opacity-50 cursor-not-allowed' : ''}`}
            >
              Download MD
            </button>
            <button 
              onClick={handleDownloadPDF}
              disabled={!reportMd}
              className={`inline-flex items-center px-3 py-1.5 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none transition-colors ${!reportMd ? 'opacity-50 cursor-not-allowed' : ''}`}
            >
              Download PDF
            </button>
          </div>
        </div>
        <div className="px-6 py-5 bg-gray-50 overflow-auto max-h-[500px]">
          {/* Render markdown as HTML for better readability on screen as well */}
          <div 
            className="prose prose-sm max-w-none text-gray-700" 
            dangerouslySetInnerHTML={{ __html: marked.parse(reportMd || 'Report pending generation...') as string }} 
          />
        </div>
      </div>
      
    </div>
  );
};

export default ResultsPage;